name: Issue
on:
   issues:
jobs:
  hello:
    runs-on: ubuntu-latest
    env:
      MY_SECRET: ${{ secrets.MY_SECRET }}
    steps:
      - run: |
            echo "New issue: ${{ github.event.issue.title }}"
