name: CI
on:
  workflow_dispatch:
    inputs:
      input-string:
        description: 'input'
        type: string
        required: true

jobs:
 test:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout code
       uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
     
     - name: Test ls
       run: ls $GITHUB_WORKSPACE   
     
     - name: Test input
       run: title="${{ inputs.input-string }}"
     
     - name: Test input via env
       env:
         TITLE: ${{ inputs.input-string }}
       run: | 
         title="$TITLE"
         echo "$title"
