name: CI
on:
  workflow_dispatch:
    inputs:
      input-string:
        description: 'input'
        type: string
        required: true

jobs:
 test:
   runs-on: ubuntu-latest
   steps:
     - name: test
       run: "echo ${{ inputs.input-string }}"
