name: Production Release Process

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: test
        env:
          VERSION_ENV: ${{ inputs.version }}
        run: |
          VERSION_INP="${{ inputs.version }}"
          echo "${VERSION_INP%-*}"
          echo "${VERSION_ENV%-*}"
  
